//People
export const FETCHING_PEOPLE = 'FETCHING_PEOPLE'
export const FETCHING_PEOPLE_SUCCESS = 'FETCHING_PEOPLE_SUCCESS'
export const FETCHING_PEOPLE_FAILURE = 'FETCHING_PEOPLE_FAILURE'

//Clear
export const CLEAR_LIST = 'CLEAR_LIST'
